name: focus_quest_example
description: Example application for the focus_quest package.
publish_to: 'none'

environment:
  sdk: ^3.12.1
  flutter: '>=3.44.1'

dependencies:
  flutter:
    sdk: flutter
  focus_quest:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.3.3

flutter:
  uses-material-design: true
